### ISSUE TITLE
Missing resources in `dist`

### ISSUE THREAD

**Issue by dnlkoch** [terrestris/react-util#483]
The images files [geolocation-marker-heading.png](https://github.com/terrestris/react-util/blob/main/src/hooks/useGeoLocation/geolocation-marker-heading.png) and [geolocation-marker.png](https://github.com/terrestris/react-util/blob/main/src/hooks/useGeoLocation/geolocation-marker.png) are missing in the current distribution.

**Comment by ahennr** [comment]
Can this be closed @dnlkoch ?
